// Mocks generated by Mockito 5.4.4 from annotations
// in Flavorly/test/features/home/helper/test_helper.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i9;

import 'package:dartz/dartz.dart' as _i2;
import 'package:dio/src/adapter.dart' as _i4;
import 'package:dio/src/cancel_token.dart' as _i17;
import 'package:dio/src/dio.dart' as _i16;
import 'package:dio/src/dio_mixin.dart' as _i6;
import 'package:dio/src/options.dart' as _i3;
import 'package:dio/src/response.dart' as _i7;
import 'package:dio/src/transformer.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:Flavorly/core/error/failure.dart' as _i10;
import 'package:Flavorly/core/network/network_info.dart' as _i24;
import 'package:Flavorly/features/home/data/data_sources/remote/remote_data_source.dart'
    as _i18;
import 'package:Flavorly/features/home/data/models/category_model.dart' as _i19;
import 'package:Flavorly/features/home/data/models/menu_recipe_model.dart'
    as _i23;
import 'package:Flavorly/features/home/data/models/nutrient_recipe_model.dart'
    as _i22;
import 'package:Flavorly/features/home/data/models/random_recipe_model.dart'
    as _i21;
import 'package:Flavorly/features/home/data/models/recommended_item_model.dart'
    as _i20;
import 'package:Flavorly/features/home/domain/entites/category_recipe_entity.dart'
    as _i11;
import 'package:Flavorly/features/home/domain/entites/menu_recipe_entiry.dart'
    as _i15;
import 'package:Flavorly/features/home/domain/entites/Nutrients_recipe_entity.dart'
    as _i13;
import 'package:Flavorly/features/home/domain/entites/random_recipe_entity.dart'
    as _i14;
import 'package:Flavorly/features/home/domain/entites/recommend_recipe_entity.dart'
    as _i12;
import 'package:Flavorly/features/home/domain/repositories/home_repository.dart'
    as _i8;
import 'package:Flavorly/features/home/domain/usecases/get_categories_recipes_use_case.dart'
    as _i25;
import 'package:Flavorly/features/home/domain/usecases/get_menu_recipe_use_case.dart'
    as _i27;
import 'package:Flavorly/features/home/domain/usecases/get_recipies_by_nutrients.dart'
    as _i26;
import 'package:Flavorly/features/home/domain/usecases/get_recommended_item_usecase.dart'
    as _i28;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBaseOptions_1 extends _i1.SmartFake implements _i3.BaseOptions {
  _FakeBaseOptions_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeHttpClientAdapter_2 extends _i1.SmartFake
    implements _i4.HttpClientAdapter {
  _FakeHttpClientAdapter_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTransformer_3 extends _i1.SmartFake implements _i5.Transformer {
  _FakeTransformer_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeInterceptors_4 extends _i1.SmartFake implements _i6.Interceptors {
  _FakeInterceptors_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResponse_5<T1> extends _i1.SmartFake implements _i7.Response<T1> {
  _FakeResponse_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeHomeRepository_6 extends _i1.SmartFake
    implements _i8.HomeRepository {
  _FakeHomeRepository_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [HomeRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockHomeRepository extends _i1.Mock implements _i8.HomeRepository {
  MockHomeRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<_i2.Either<_i10.Failure, List<_i11.CategoryEntity>>>
      getCategoriesOfRecipes(String? cuisine) => (super.noSuchMethod(
            Invocation.method(
              #getCategoriesOfRecipes,
              [cuisine],
            ),
            returnValue: _i9.Future<
                    _i2.Either<_i10.Failure, List<_i11.CategoryEntity>>>.value(
                _FakeEither_0<_i10.Failure, List<_i11.CategoryEntity>>(
              this,
              Invocation.method(
                #getCategoriesOfRecipes,
                [cuisine],
              ),
            )),
          ) as _i9.Future<_i2.Either<_i10.Failure, List<_i11.CategoryEntity>>>);

  @override
  _i9.Future<_i2.Either<_i10.Failure, List<_i12.RecommendRecipeEntity>>>
      getRecommendedRecipes(int? id) => (super.noSuchMethod(
            Invocation.method(
              #getRecommendedRecipes,
              [id],
            ),
            returnValue: _i9.Future<
                    _i2.Either<_i10.Failure,
                        List<_i12.RecommendRecipeEntity>>>.value(
                _FakeEither_0<_i10.Failure, List<_i12.RecommendRecipeEntity>>(
              this,
              Invocation.method(
                #getRecommendedRecipes,
                [id],
              ),
            )),
          ) as _i9.Future<
              _i2.Either<_i10.Failure, List<_i12.RecommendRecipeEntity>>>);

  @override
  _i9.Future<_i2.Either<_i10.Failure, List<_i13.NutrientRecipeEntity>>>
      getRecipesByNutrients(
    List<String>? nutrients,
    int? concentration,
  ) =>
          (super.noSuchMethod(
            Invocation.method(
              #getRecipesByNutrients,
              [
                nutrients,
                concentration,
              ],
            ),
            returnValue: _i9.Future<
                    _i2.Either<_i10.Failure,
                        List<_i13.NutrientRecipeEntity>>>.value(
                _FakeEither_0<_i10.Failure, List<_i13.NutrientRecipeEntity>>(
              this,
              Invocation.method(
                #getRecipesByNutrients,
                [
                  nutrients,
                  concentration,
                ],
              ),
            )),
          ) as _i9.Future<
              _i2.Either<_i10.Failure, List<_i13.NutrientRecipeEntity>>>);

  @override
  _i9.Future<
      _i2.Either<_i10.Failure, List<_i14.RandomRecipeEntity>>> getRandomRecipes(
          int? number) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRandomRecipes,
          [number],
        ),
        returnValue: _i9.Future<
                _i2.Either<_i10.Failure, List<_i14.RandomRecipeEntity>>>.value(
            _FakeEither_0<_i10.Failure, List<_i14.RandomRecipeEntity>>(
          this,
          Invocation.method(
            #getRandomRecipes,
            [number],
          ),
        )),
      ) as _i9.Future<_i2.Either<_i10.Failure, List<_i14.RandomRecipeEntity>>>);

  @override
  _i9.Future<
      _i2.Either<_i10.Failure, List<_i15.MenuRecipeEntity>>> getMenuItems(
    String? menuItem,
    int? number,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMenuItems,
          [
            menuItem,
            number,
          ],
        ),
        returnValue: _i9.Future<
                _i2.Either<_i10.Failure, List<_i15.MenuRecipeEntity>>>.value(
            _FakeEither_0<_i10.Failure, List<_i15.MenuRecipeEntity>>(
          this,
          Invocation.method(
            #getMenuItems,
            [
              menuItem,
              number,
            ],
          ),
        )),
      ) as _i9.Future<_i2.Either<_i10.Failure, List<_i15.MenuRecipeEntity>>>);
}

/// A class which mocks [Dio].
///
/// See the documentation for Mockito's code generation for more information.
class MockDio extends _i1.Mock implements _i16.Dio {
  MockDio() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.BaseOptions get options => (super.noSuchMethod(
        Invocation.getter(#options),
        returnValue: _FakeBaseOptions_1(
          this,
          Invocation.getter(#options),
        ),
      ) as _i3.BaseOptions);

  @override
  set options(_i3.BaseOptions? _options) => super.noSuchMethod(
        Invocation.setter(
          #options,
          _options,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.HttpClientAdapter get httpClientAdapter => (super.noSuchMethod(
        Invocation.getter(#httpClientAdapter),
        returnValue: _FakeHttpClientAdapter_2(
          this,
          Invocation.getter(#httpClientAdapter),
        ),
      ) as _i4.HttpClientAdapter);

  @override
  set httpClientAdapter(_i4.HttpClientAdapter? _httpClientAdapter) =>
      super.noSuchMethod(
        Invocation.setter(
          #httpClientAdapter,
          _httpClientAdapter,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Transformer get transformer => (super.noSuchMethod(
        Invocation.getter(#transformer),
        returnValue: _FakeTransformer_3(
          this,
          Invocation.getter(#transformer),
        ),
      ) as _i5.Transformer);

  @override
  set transformer(_i5.Transformer? _transformer) => super.noSuchMethod(
        Invocation.setter(
          #transformer,
          _transformer,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Interceptors get interceptors => (super.noSuchMethod(
        Invocation.getter(#interceptors),
        returnValue: _FakeInterceptors_4(
          this,
          Invocation.getter(#interceptors),
        ),
      ) as _i6.Interceptors);

  @override
  void close({bool? force = false}) => super.noSuchMethod(
        Invocation.method(
          #close,
          [],
          {#force: force},
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i9.Future<_i7.Response<T>> head<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i3.Options? options,
    _i17.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #head,
          [path],
          {
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
          },
        ),
        returnValue: _i9.Future<_i7.Response<T>>.value(_FakeResponse_5<T>(
          this,
          Invocation.method(
            #head,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #options: options,
              #cancelToken: cancelToken,
            },
          ),
        )),
      ) as _i9.Future<_i7.Response<T>>);

  @override
  _i9.Future<_i7.Response<T>> headUri<T>(
    Uri? uri, {
    Object? data,
    _i3.Options? options,
    _i17.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #headUri,
          [uri],
          {
            #data: data,
            #options: options,
            #cancelToken: cancelToken,
          },
        ),
        returnValue: _i9.Future<_i7.Response<T>>.value(_FakeResponse_5<T>(
          this,
          Invocation.method(
            #headUri,
            [uri],
            {
              #data: data,
              #options: options,
              #cancelToken: cancelToken,
            },
          ),
        )),
      ) as _i9.Future<_i7.Response<T>>);

  @override
  _i9.Future<_i7.Response<T>> get<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i3.Options? options,
    _i17.CancelToken? cancelToken,
    _i3.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [path],
          {
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i9.Future<_i7.Response<T>>.value(_FakeResponse_5<T>(
          this,
          Invocation.method(
            #get,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #options: options,
              #cancelToken: cancelToken,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i9.Future<_i7.Response<T>>);

  @override
  _i9.Future<_i7.Response<T>> getUri<T>(
    Uri? uri, {
    Object? data,
    _i3.Options? options,
    _i17.CancelToken? cancelToken,
    _i3.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUri,
          [uri],
          {
            #data: data,
            #options: options,
            #cancelToken: cancelToken,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i9.Future<_i7.Response<T>>.value(_FakeResponse_5<T>(
          this,
          Invocation.method(
            #getUri,
            [uri],
            {
              #data: data,
              #options: options,
              #cancelToken: cancelToken,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i9.Future<_i7.Response<T>>);

  @override
  _i9.Future<_i7.Response<T>> post<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i3.Options? options,
    _i17.CancelToken? cancelToken,
    _i3.ProgressCallback? onSendProgress,
    _i3.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [path],
          {
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i9.Future<_i7.Response<T>>.value(_FakeResponse_5<T>(
          this,
          Invocation.method(
            #post,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #options: options,
              #cancelToken: cancelToken,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i9.Future<_i7.Response<T>>);

  @override
  _i9.Future<_i7.Response<T>> postUri<T>(
    Uri? uri, {
    Object? data,
    _i3.Options? options,
    _i17.CancelToken? cancelToken,
    _i3.ProgressCallback? onSendProgress,
    _i3.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #postUri,
          [uri],
          {
            #data: data,
            #options: options,
            #cancelToken: cancelToken,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i9.Future<_i7.Response<T>>.value(_FakeResponse_5<T>(
          this,
          Invocation.method(
            #postUri,
            [uri],
            {
              #data: data,
              #options: options,
              #cancelToken: cancelToken,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i9.Future<_i7.Response<T>>);

  @override
  _i9.Future<_i7.Response<T>> put<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i3.Options? options,
    _i17.CancelToken? cancelToken,
    _i3.ProgressCallback? onSendProgress,
    _i3.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [path],
          {
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i9.Future<_i7.Response<T>>.value(_FakeResponse_5<T>(
          this,
          Invocation.method(
            #put,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #options: options,
              #cancelToken: cancelToken,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i9.Future<_i7.Response<T>>);

  @override
  _i9.Future<_i7.Response<T>> putUri<T>(
    Uri? uri, {
    Object? data,
    _i3.Options? options,
    _i17.CancelToken? cancelToken,
    _i3.ProgressCallback? onSendProgress,
    _i3.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #putUri,
          [uri],
          {
            #data: data,
            #options: options,
            #cancelToken: cancelToken,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i9.Future<_i7.Response<T>>.value(_FakeResponse_5<T>(
          this,
          Invocation.method(
            #putUri,
            [uri],
            {
              #data: data,
              #options: options,
              #cancelToken: cancelToken,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i9.Future<_i7.Response<T>>);

  @override
  _i9.Future<_i7.Response<T>> patch<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i3.Options? options,
    _i17.CancelToken? cancelToken,
    _i3.ProgressCallback? onSendProgress,
    _i3.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #patch,
          [path],
          {
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i9.Future<_i7.Response<T>>.value(_FakeResponse_5<T>(
          this,
          Invocation.method(
            #patch,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #options: options,
              #cancelToken: cancelToken,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i9.Future<_i7.Response<T>>);

  @override
  _i9.Future<_i7.Response<T>> patchUri<T>(
    Uri? uri, {
    Object? data,
    _i3.Options? options,
    _i17.CancelToken? cancelToken,
    _i3.ProgressCallback? onSendProgress,
    _i3.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #patchUri,
          [uri],
          {
            #data: data,
            #options: options,
            #cancelToken: cancelToken,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i9.Future<_i7.Response<T>>.value(_FakeResponse_5<T>(
          this,
          Invocation.method(
            #patchUri,
            [uri],
            {
              #data: data,
              #options: options,
              #cancelToken: cancelToken,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i9.Future<_i7.Response<T>>);

  @override
  _i9.Future<_i7.Response<T>> delete<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i3.Options? options,
    _i17.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [path],
          {
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
          },
        ),
        returnValue: _i9.Future<_i7.Response<T>>.value(_FakeResponse_5<T>(
          this,
          Invocation.method(
            #delete,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #options: options,
              #cancelToken: cancelToken,
            },
          ),
        )),
      ) as _i9.Future<_i7.Response<T>>);

  @override
  _i9.Future<_i7.Response<T>> deleteUri<T>(
    Uri? uri, {
    Object? data,
    _i3.Options? options,
    _i17.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteUri,
          [uri],
          {
            #data: data,
            #options: options,
            #cancelToken: cancelToken,
          },
        ),
        returnValue: _i9.Future<_i7.Response<T>>.value(_FakeResponse_5<T>(
          this,
          Invocation.method(
            #deleteUri,
            [uri],
            {
              #data: data,
              #options: options,
              #cancelToken: cancelToken,
            },
          ),
        )),
      ) as _i9.Future<_i7.Response<T>>);

  @override
  _i9.Future<_i7.Response<dynamic>> download(
    String? urlPath,
    dynamic savePath, {
    _i3.ProgressCallback? onReceiveProgress,
    Map<String, dynamic>? queryParameters,
    _i17.CancelToken? cancelToken,
    bool? deleteOnError = true,
    String? lengthHeader = r'content-length',
    Object? data,
    _i3.Options? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #download,
          [
            urlPath,
            savePath,
          ],
          {
            #onReceiveProgress: onReceiveProgress,
            #queryParameters: queryParameters,
            #cancelToken: cancelToken,
            #deleteOnError: deleteOnError,
            #lengthHeader: lengthHeader,
            #data: data,
            #options: options,
          },
        ),
        returnValue:
            _i9.Future<_i7.Response<dynamic>>.value(_FakeResponse_5<dynamic>(
          this,
          Invocation.method(
            #download,
            [
              urlPath,
              savePath,
            ],
            {
              #onReceiveProgress: onReceiveProgress,
              #queryParameters: queryParameters,
              #cancelToken: cancelToken,
              #deleteOnError: deleteOnError,
              #lengthHeader: lengthHeader,
              #data: data,
              #options: options,
            },
          ),
        )),
      ) as _i9.Future<_i7.Response<dynamic>>);

  @override
  _i9.Future<_i7.Response<dynamic>> downloadUri(
    Uri? uri,
    dynamic savePath, {
    _i3.ProgressCallback? onReceiveProgress,
    _i17.CancelToken? cancelToken,
    bool? deleteOnError = true,
    String? lengthHeader = r'content-length',
    Object? data,
    _i3.Options? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #downloadUri,
          [
            uri,
            savePath,
          ],
          {
            #onReceiveProgress: onReceiveProgress,
            #cancelToken: cancelToken,
            #deleteOnError: deleteOnError,
            #lengthHeader: lengthHeader,
            #data: data,
            #options: options,
          },
        ),
        returnValue:
            _i9.Future<_i7.Response<dynamic>>.value(_FakeResponse_5<dynamic>(
          this,
          Invocation.method(
            #downloadUri,
            [
              uri,
              savePath,
            ],
            {
              #onReceiveProgress: onReceiveProgress,
              #cancelToken: cancelToken,
              #deleteOnError: deleteOnError,
              #lengthHeader: lengthHeader,
              #data: data,
              #options: options,
            },
          ),
        )),
      ) as _i9.Future<_i7.Response<dynamic>>);

  @override
  _i9.Future<_i7.Response<T>> request<T>(
    String? url, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i17.CancelToken? cancelToken,
    _i3.Options? options,
    _i3.ProgressCallback? onSendProgress,
    _i3.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #request,
          [url],
          {
            #data: data,
            #queryParameters: queryParameters,
            #cancelToken: cancelToken,
            #options: options,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i9.Future<_i7.Response<T>>.value(_FakeResponse_5<T>(
          this,
          Invocation.method(
            #request,
            [url],
            {
              #data: data,
              #queryParameters: queryParameters,
              #cancelToken: cancelToken,
              #options: options,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i9.Future<_i7.Response<T>>);

  @override
  _i9.Future<_i7.Response<T>> requestUri<T>(
    Uri? uri, {
    Object? data,
    _i17.CancelToken? cancelToken,
    _i3.Options? options,
    _i3.ProgressCallback? onSendProgress,
    _i3.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #requestUri,
          [uri],
          {
            #data: data,
            #cancelToken: cancelToken,
            #options: options,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i9.Future<_i7.Response<T>>.value(_FakeResponse_5<T>(
          this,
          Invocation.method(
            #requestUri,
            [uri],
            {
              #data: data,
              #cancelToken: cancelToken,
              #options: options,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i9.Future<_i7.Response<T>>);

  @override
  _i9.Future<_i7.Response<T>> fetch<T>(_i3.RequestOptions? requestOptions) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetch,
          [requestOptions],
        ),
        returnValue: _i9.Future<_i7.Response<T>>.value(_FakeResponse_5<T>(
          this,
          Invocation.method(
            #fetch,
            [requestOptions],
          ),
        )),
      ) as _i9.Future<_i7.Response<T>>);
}

/// A class which mocks [HomeRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockHomeRemoteDataSource extends _i1.Mock
    implements _i18.HomeRemoteDataSource {
  MockHomeRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<List<_i19.CategoryModel>> getCategoriesOfRecipes(
          String? category) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCategoriesOfRecipes,
          [category],
        ),
        returnValue:
            _i9.Future<List<_i19.CategoryModel>>.value(<_i19.CategoryModel>[]),
      ) as _i9.Future<List<_i19.CategoryModel>>);

  @override
  _i9.Future<List<_i20.RecommendedRecipeModel>> getRecommendedRecipes(
          int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecommendedRecipes,
          [id],
        ),
        returnValue: _i9.Future<List<_i20.RecommendedRecipeModel>>.value(
            <_i20.RecommendedRecipeModel>[]),
      ) as _i9.Future<List<_i20.RecommendedRecipeModel>>);

  @override
  _i9.Future<List<_i21.RandomRecipeModel>> getRandomRecipes(int? number) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRandomRecipes,
          [number],
        ),
        returnValue: _i9.Future<List<_i21.RandomRecipeModel>>.value(
            <_i21.RandomRecipeModel>[]),
      ) as _i9.Future<List<_i21.RandomRecipeModel>>);

  @override
  _i9.Future<List<_i22.NutrientRecipeModel>> getNutrientRecipes(
    List<String>? query,
    int? concentration,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getNutrientRecipes,
          [
            query,
            concentration,
          ],
        ),
        returnValue: _i9.Future<List<_i22.NutrientRecipeModel>>.value(
            <_i22.NutrientRecipeModel>[]),
      ) as _i9.Future<List<_i22.NutrientRecipeModel>>);

  @override
  _i9.Future<List<_i23.MenuRecipeModel>> getMenuRecipes(
    String? menuItem,
    int? number,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMenuRecipes,
          [
            menuItem,
            number,
          ],
        ),
        returnValue: _i9.Future<List<_i23.MenuRecipeModel>>.value(
            <_i23.MenuRecipeModel>[]),
      ) as _i9.Future<List<_i23.MenuRecipeModel>>);
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i24.NetworkInfo {
  MockNetworkInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<bool> get isConnected => (super.noSuchMethod(
        Invocation.getter(#isConnected),
        returnValue: _i9.Future<bool>.value(false),
      ) as _i9.Future<bool>);
}

/// A class which mocks [GetCategoriesRecipesUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetCategoriesRecipesUseCase extends _i1.Mock
    implements _i25.GetCategoriesRecipesUseCase {
  MockGetCategoriesRecipesUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.HomeRepository get homeRepository => (super.noSuchMethod(
        Invocation.getter(#homeRepository),
        returnValue: _FakeHomeRepository_6(
          this,
          Invocation.getter(#homeRepository),
        ),
      ) as _i8.HomeRepository);

  @override
  _i9.Future<_i2.Either<_i10.Failure, List<_i11.CategoryEntity>>> call(
          _i25.CategoriesParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i9
            .Future<_i2.Either<_i10.Failure, List<_i11.CategoryEntity>>>.value(
            _FakeEither_0<_i10.Failure, List<_i11.CategoryEntity>>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i9.Future<_i2.Either<_i10.Failure, List<_i11.CategoryEntity>>>);
}

/// A class which mocks [GetRecipesByNutrientsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetRecipesByNutrientsUseCase extends _i1.Mock
    implements _i26.GetRecipesByNutrientsUseCase {
  MockGetRecipesByNutrientsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.HomeRepository get homeRepository => (super.noSuchMethod(
        Invocation.getter(#homeRepository),
        returnValue: _FakeHomeRepository_6(
          this,
          Invocation.getter(#homeRepository),
        ),
      ) as _i8.HomeRepository);

  @override
  _i9.Future<_i2.Either<_i10.Failure, List<_i13.NutrientRecipeEntity>>> call(
          _i26.NutrientsParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i9.Future<
                _i2
                .Either<_i10.Failure, List<_i13.NutrientRecipeEntity>>>.value(
            _FakeEither_0<_i10.Failure, List<_i13.NutrientRecipeEntity>>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i9
          .Future<_i2.Either<_i10.Failure, List<_i13.NutrientRecipeEntity>>>);
}

/// A class which mocks [GetMenuRecipeUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetMenuRecipeUseCase extends _i1.Mock
    implements _i27.GetMenuRecipeUseCase {
  MockGetMenuRecipeUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.HomeRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeHomeRepository_6(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i8.HomeRepository);

  @override
  _i9.Future<_i2.Either<_i10.Failure, List<_i15.MenuRecipeEntity>>> call(
          _i27.MenuRecipeParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i9.Future<
                _i2.Either<_i10.Failure, List<_i15.MenuRecipeEntity>>>.value(
            _FakeEither_0<_i10.Failure, List<_i15.MenuRecipeEntity>>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i9.Future<_i2.Either<_i10.Failure, List<_i15.MenuRecipeEntity>>>);
}

/// A class which mocks [GetRecommendedItemUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetRecommendedItemUseCase extends _i1.Mock
    implements _i28.GetRecommendedItemUseCase {
  MockGetRecommendedItemUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.HomeRepository get homeRepository => (super.noSuchMethod(
        Invocation.getter(#homeRepository),
        returnValue: _FakeHomeRepository_6(
          this,
          Invocation.getter(#homeRepository),
        ),
      ) as _i8.HomeRepository);

  @override
  _i9.Future<_i2.Either<_i10.Failure, List<_i12.RecommendRecipeEntity>>> call(
          _i28.RecommendedRecipeParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i9.Future<
                _i2
                .Either<_i10.Failure, List<_i12.RecommendRecipeEntity>>>.value(
            _FakeEither_0<_i10.Failure, List<_i12.RecommendRecipeEntity>>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i9
          .Future<_i2.Either<_i10.Failure, List<_i12.RecommendRecipeEntity>>>);
}
