const apiKey = '2c1b0e52091f4f3696b5642181e5d4b6';
// recommeded = https://api.spoonacular.com/recipes/random
// popular = https://api.spoonacular.com/recipes/search?apiKey=2c1b0e52091f4f3696b5642181e5d4b6&number=10&cuisine=indian
List<String> categories = [
  "American",
  "Indian",
  "Italian",
  "Chinese",
  "Japanese",
  "Mexican",
  "French",
  "Spanish",
  "Thai",
  "Greek",
  "Mediterranean",
  "Middle Eastern",
  "Vietnamese",
  "Brazilian",
  "Argentinian",
  "African",
  "Caribbean",
  "Korean",
  "Turkish",
  "Russian",
  "Scandinavian",
  "Australian",
  "British",
  "Irish",
  "German",
];
