// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbQE5bzFOAw8yBssq3LTcUPva12CNoYEM',
    appId: '1:523679251880:web:eaec6867465e5b040f719d',
    messagingSenderId: '523679251880',
    projectId: 'recipeapp-92364',
    authDomain: 'recipeapp-92364.firebaseapp.com',
    storageBucket: 'recipeapp-92364.appspot.com',
    measurementId: 'G-JC50260XNP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHtNs6CiRArJJnFMfKCaGk2-KS7ELKDP0',
    appId: '1:523679251880:android:293665472a583cf70f719d',
    messagingSenderId: '523679251880',
    projectId: 'recipeapp-92364',
    storageBucket: 'recipeapp-92364.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfCIIBUCSTtdWYXWQR59357WTDQc8DvhI',
    appId: '1:523679251880:ios:de7951e1ccbad4aa0f719d',
    messagingSenderId: '523679251880',
    projectId: 'recipeapp-92364',
    storageBucket: 'recipeapp-92364.appspot.com',
    iosBundleId: 'com.example.recipeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfCIIBUCSTtdWYXWQR59357WTDQc8DvhI',
    appId: '1:523679251880:ios:dc0177b861d8da8c0f719d',
    messagingSenderId: '523679251880',
    projectId: 'recipeapp-92364',
    storageBucket: 'recipeapp-92364.appspot.com',
    iosBundleId: 'com.example.recipeApp.RunnerTests',
  );
}
